### ISSUE TITLE
您好！运行之后没有结果

### ISSUE THREAD

**Issue by Rsweater** [Andy-cumt/RASDF_GUI#1]
不知道为什么运行之后没有结果，只有hdr文件。cpu占用下去了，但是程序没有任何反应，是不是还没运行完？我的数据是1920*1920的，每一个像素30m，能否加个联系方式（微信：W9264736944）请教一下

**Comment by Andy-cumt** [comment]
> 不知道为什么运行之后没有结果，只有hdr文件。cpu占用下去了，但是程序没有任何反应，是不是还没运行完？我的数据是1920*1920的，每一个像素30m，能否加个联系方式（微信：W9264736944）请教一下

你好！非常感谢使用我们的程序，请问低分辨率影像和高分辨率影像都是1920*1920的吗，是否输入了输出的路径和文件名，测试文件是否能正常跑通？

**Comment by Rsweater** [comment]
嗯嗯  都是1920×1920的，测试文件刚试了下，也是一样     不知道为什么cpu占用下去之后，仍然没有结果，只多了一个hdr头文件，没有影像文件
![image](https://user-images.githubusercontent.com/49091147/166099225-68562470-e3b2-489e-af14-c913a005dbd5.png)
![image](https://user-images.githubusercontent.com/49091147/166099351-5328b5d4-6809-415b-9e68-48cdf7b3ccef.png)

**Comment by Andy-cumt** [comment]
> 嗯嗯 都是1920×1920的，测试文件刚试了下，也是一样 不知道为什么cpu占用下去之后，仍然没有结果，只多了一个hdr头文件，没有影像文件 ![image](https://user-images.githubusercontent.com/49091147/166099225-68562470-e3b2-489e-af14-c913a005dbd5.png) ![image](https://user-images.githubusercontent.com/49091147/166099351-5328b5d4-6809-415b-9e68-48cdf7b3ccef.png)

"Path of output needs to contain the file name of the output image"——Readme.docx

**Comment by Rsweater** [comment]
> Path of output needs to contain the file name of the output image

谢谢前辈，已知问题（当时我理解有误），已运行成功。给您添麻烦了

**Comment by Andy-cumt** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不客气的，有问题可以随时联系。感谢使用我们的程序！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月1日 ***@***.***> 写道： 






Path of output needs to contain the file name of the output image



谢谢前辈，已知问题（当时我理解有误），已运行成功。给您添麻烦了
